#!/bin/sh /etc/rc.common
START=96
STOP=14
USE_PROCD=1

WATCHDOG=/usr/lib/podkop_bot/warpscout-rescue-watchdog

start_service() {
	[ -f "$WATCHDOG" ] || return 0
	procd_open_instance
	procd_set_param command /bin/sh "$WATCHDOG"
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
